import type { StrategyData } from '@/context/StrategyContext'
import type { StrategyOutput } from '@/data/strategy-generator'

/**
 * Generate markdown representation of strategy
 */
export function generateMarkdown(strategy: StrategyData, output: StrategyOutput): string {
  const lines: string[] = []

  lines.push(`# Strategy: ${strategy.yourTeam} vs ${strategy.opponentTeam}`)
  lines.push(`**Map:** ${strategy.map} | **Generated:** ${new Date(strategy.timestamp).toLocaleString()}`)
  lines.push('')

  // Overview
  lines.push('## 📊 Overview')
  lines.push(output.overview.matchupAnalysis)
  lines.push('')
  lines.push('### ✅ Key Advantages')
  output.overview.keyAdvantages.forEach((adv) => {
    lines.push(`- ${adv}`)
  })
  lines.push('')

  lines.push('### ⚠️ Key Threats')
  output.overview.keyThreats.forEach((threat) => {
    lines.push(`- ${threat}`)
  })
  lines.push('')

  lines.push('### 🎯 Recommended Approach')
  lines.push(`> ${output.overview.recommendedApproach}`)
  lines.push('')

  // Agent Composition
  lines.push('## 👥 Agent Composition')
  lines.push(output.agentComposition.compositionRationale)
  lines.push('')

  lines.push('| Agent | Role | Player | Reasoning |')
  lines.push('|-------|------|--------|-----------|')
  output.agentComposition.agents.forEach((agent) => {
    lines.push(`| ${agent.agent} | ${agent.role} | ${agent.player} | ${agent.reasoning} |`)
  })
  lines.push('')

  // Pistol Rounds
  lines.push('## 🔫 Pistol Rounds')

  lines.push('### 🔴 Attack')
  lines.push(output.pistolRounds.attack.strategy)
  lines.push('')
  lines.push('**Setup:**')
  output.pistolRounds.attack.setup.forEach((s) => {
    lines.push(`- ${s.player} (${s.agent}) - ${s.position}: ${s.responsibility}`)
  })
  lines.push('')
  lines.push(`**Win Condition:** ${output.pistolRounds.attack.winCondition}`)
  lines.push('')

  lines.push('### 🔵 Defense')
  lines.push(output.pistolRounds.defense.strategy)
  lines.push('')
  lines.push('**Setup:**')
  output.pistolRounds.defense.setup.forEach((s) => {
    lines.push(`- ${s.player} (${s.agent}) - ${s.position}: ${s.responsibility}`)
  })
  lines.push('')
  lines.push(`**Win Condition:** ${output.pistolRounds.defense.winCondition}`)
  lines.push('')

  // Round Timeline
  lines.push('## ⏱️ Round Timeline')

  lines.push('### 🔴 Attack')
  output.roundTimeline.gunRoundAttack.forEach((block) => {
    lines.push(`**${block.timeRange} - ${block.phase}**`)
    lines.push('Actions:')
    block.actions.forEach((a) => lines.push(`- ${a}`))
    lines.push('Key Decisions:')
    block.keyDecisions.forEach((d) => lines.push(`- ✓ ${d}`))
    lines.push('')
  })

  lines.push('### 🔵 Defense')
  output.roundTimeline.gunRoundDefense.forEach((block) => {
    lines.push(`**${block.timeRange} - ${block.phase}**`)
    lines.push('Actions:')
    block.actions.forEach((a) => lines.push(`- ${a}`))
    lines.push('Key Decisions:')
    block.keyDecisions.forEach((d) => lines.push(`- ✓ ${d}`))
    lines.push('')
  })

  // Counter Strategy
  lines.push('## 🛡️ Counter-Strategy')
  lines.push('### Opponent Weaknesses to Exploit')
  output.counterStrategy.opponentWeaknesses.forEach((w) => {
    lines.push(`- **${w.weakness}** (${w.timing}): ${w.howToExploit}`)
  })
  lines.push('')

  lines.push('### Opponent Strengths to Neutralize')
  output.counterStrategy.opponentStrengths.forEach((s) => {
    lines.push(`- **${s.strength}**: ${s.howToNeutralize} (Avoid: ${s.avoidance})`)
  })
  lines.push('')

  lines.push('### Adaptation Triggers')
  output.counterStrategy.adaptationTriggers.forEach((t) => {
    lines.push(`- **${t.situation}** → ${t.adjustment}`)
  })
  lines.push('')

  // Footer
  lines.push('---')
  lines.push('_Generated by Emergent AI Strategy Generator_')

  return lines.join('\n')
}

/**
 * Copy markdown to clipboard
 */
export async function copyToClipboard(strategy: StrategyData, output: StrategyOutput) {
  const markdown = generateMarkdown(strategy, output)
  try {
    await navigator.clipboard.writeText(markdown)
    return { success: true, message: 'Strategy copied to clipboard!' }
  } catch (error) {
    console.error('Failed to copy:', error)
    return { success: false, message: 'Failed to copy to clipboard' }
  }
}

/**
 * Generate shareable link (in a real app, this would upload to a server)
 * For now, we'll create a data URL with the strategy encoded
 */
export function generateShareableLink(strategy: StrategyData, output: StrategyOutput): string {
  const data = {
    strategy: {
      map: strategy.map,
      yourTeam: strategy.yourTeam,
      opponentTeam: strategy.opponentTeam,
      timestamp: strategy.timestamp,
    },
    output,
  }

  const encoded = btoa(JSON.stringify(data))
  const baseUrl = typeof window !== 'undefined' ? window.location.origin : ''

  // In a real app, you'd POST this to your backend and get a short ID
  // For now, return a data URL that could be shared
  return `${baseUrl}?strategy=${encoded.substring(0, 100)}...`
}

/**
 * Copy share link to clipboard
 */
export async function copyShareLink(strategy: StrategyData, output: StrategyOutput) {
  const link = generateShareableLink(strategy, output)
  try {
    await navigator.clipboard.writeText(link)
    return { success: true, message: 'Share link copied to clipboard!' }
  } catch (error) {
    console.error('Failed to copy share link:', error)
    return { success: false, message: 'Failed to copy share link' }
  }
}

/**
 * Download strategy as JSON
 */
export function downloadAsJSON(strategy: StrategyData, output: StrategyOutput) {
  const data = {
    ...strategy,
    output,
  }

  const dataStr = JSON.stringify(data, null, 2)
  const dataBlob = new Blob([dataStr], { type: 'application/json' })
  const url = URL.createObjectURL(dataBlob)

  const link = document.createElement('a')
  link.href = url
  link.download = `strategy_${strategy.yourTeam}_vs_${strategy.opponentTeam}_${strategy.map}.json`
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

/**
 * Export as PDF (requires a PDF library like jsPDF)
 * This is a placeholder that logs to console
 */
export async function exportAsPDF(strategy: StrategyData, output: StrategyOutput) {
  const markdown = generateMarkdown(strategy, output)

  // In a real implementation, you'd use a library like:
  // - jsPDF + html2canvas
  // - pdfkit
  // - or send to a backend PDF generation service

  console.log('PDF export would convert this markdown to PDF:')
  console.log(markdown)

  return {
    success: false,
    message: 'PDF export requires additional dependencies. Use "Copy to Clipboard" instead.',
  }
}

/**
 * Print-friendly strategy view
 */
export function openPrintView(strategy: StrategyData, output: StrategyOutput) {
  const markdown = generateMarkdown(strategy, output)

  // Convert markdown to HTML (simplified)
  let html = markdown
    .replace(/^# (.*?)$/gm, '<h1>$1</h1>')
    .replace(/^## (.*?)$/gm, '<h2>$1</h2>')
    .replace(/^### (.*?)$/gm, '<h3>$1</h3>')
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/_(.*?)_/g, '<em>$1</em>')
    .replace(/^- (.*?)$/gm, '<li>$1</li>')
    .replace(/(<li>.*?<\/li>)/s, '<ul>$1</ul>')
    .replace(/> (.*?)$/gm, '<blockquote>$1</blockquote>')
    .replace(/\n\n/g, '</p><p>')

  html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Strategy - ${strategy.yourTeam} vs ${strategy.opponentTeam}</title>
      <style>
        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
          line-height: 1.6;
          max-width: 900px;
          margin: 0 auto;
          padding: 20px;
          color: #333;
          background: white;
        }
        h1 { font-size: 2em; margin-top: 0; color: #FF4655; }
        h2 { font-size: 1.5em; color: #0095FF; margin-top: 1.5em; }
        h3 { font-size: 1.2em; color: #0ECB81; }
        table { width: 100%; border-collapse: collapse; margin: 1em 0; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background: #f5f5f5; }
        blockquote { border-left: 4px solid #FF4655; padding-left: 1em; margin: 1em 0; }
        ul { margin: 0.5em 0; padding-left: 2em; }
        @media print {
          body { padding: 0; }
          page { break-after: always; }
        }
      </style>
    </head>
    <body>
      <p>${html}</p>
    </body>
    </html>
  `

  const printWindow = window.open('', '', 'height=600,width=800')
  printWindow?.document.write(html)
  printWindow?.document.close()
  printWindow?.print()
}
